server:
  port: 9005
spring:
  application:
    name: leadnews-behavior
  kafka:
    bootstrap-servers: 192.168.65.131:9092
    consumer:
      group-id: ${spring.application.name}-kafka-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.65.132:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.65.130:3306/leadnews_behavior?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&&useSSL=false
    username: root
    password: abc123456
# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.heima.model.behavior.pojos